class ModuleGui {
public:
    // Gui related functions
#ifdef AUT_CONFIG_GUI                            // Is GUI enabled?
    AUT_RESULT    F_GUICreate(VectorVariant &vParams, Variant &vResult);
    AUT_RESULT    F_GUISwitch(VectorVariant &vParams, Variant &vResult);
    AUT_RESULT    F_GUICtrlDelete(VectorVariant &vParams, Variant &vResult);
    AUT_RESULT    F_GUICtrlCreateAvi(VectorVariant &vParams, Variant &vResult);
    AUT_RESULT    F_GUICtrlCreateButton(VectorVariant &vParams, Variant &vResult);
    AUT_RESULT    F_GUICtrlCreateCheckbox (VectorVariant &vParams, Variant &vResult);
    AUT_RESULT    F_GUICtrlCreateCombo(VectorVariant &vParams, Variant &vResult);
    AUT_RESULT    F_GUICtrlCreateContextMenu(VectorVariant &vParams, Variant &vResult);
    AUT_RESULT    F_GUICtrlCreateDate(VectorVariant &vParams, Variant &vResult);
    AUT_RESULT    F_GUICtrlCreateEdit(VectorVariant &vParams, Variant &vResult);
    AUT_RESULT    F_GUICtrlCreateGroup(VectorVariant &vParams, Variant &vResult);
    AUT_RESULT    F_GUICtrlCreateIcon(VectorVariant &vParams, Variant &vResult);
    AUT_RESULT    F_GUICtrlCreateInput(VectorVariant &vParams, Variant &vResult);
    AUT_RESULT    F_GUICtrlCreateLabel(VectorVariant &vParams, Variant &vResult);
    AUT_RESULT    F_GUICtrlCreateList(VectorVariant &vParams, Variant &vResult);
    AUT_RESULT    F_GUICtrlCreateMenu(VectorVariant &vParams, Variant &vResult);
    AUT_RESULT    F_GUICtrlCreateMenuItem(VectorVariant &vParams, Variant &vResult);
    AUT_RESULT    F_GUICtrlCreatePic(VectorVariant &vParams, Variant &vResult);
    AUT_RESULT    F_GUICtrlCreateProgress(VectorVariant &vParams, Variant &vResult);
    AUT_RESULT    F_GUICtrlCreateRadio(VectorVariant &vParams, Variant &vResult);
    AUT_RESULT    F_GUICtrlCreateSlider(VectorVariant &vParams, Variant &vResult);
    AUT_RESULT    F_GUICtrlCreateTab(VectorVariant &vParams, Variant &vResult);
    AUT_RESULT    F_GUICtrlCreateTabitem(VectorVariant &vParams, Variant &vResult);
    AUT_RESULT    F_GUICtrlCreateTrayMenu(VectorVariant &vParams, Variant &vResult);
    AUT_RESULT    F_GUICtrlCreateTreeView(VectorVariant &vParams, Variant &vResult);
    AUT_RESULT    F_GUICtrlCreateTreeViewItem(VectorVariant &vParams, Variant &vResult);
    AUT_RESULT    F_GUICtrlCreateListView(VectorVariant &vParams, Variant &vResult);
    AUT_RESULT    F_GUICtrlCreateListViewItem(VectorVariant &vParams, Variant &vResult);
    AUT_RESULT    F_GUICtrlCreateUpdown(VectorVariant &vParams, Variant &vResult);
    AUT_RESULT    F_GUICtrlCreateDummy(VectorVariant &vParams, Variant &vResult);
    AUT_RESULT    GUICtrlCreate(int nType, VectorVariant &vParams, Variant &vResult);
    AUT_RESULT    F_GUICtrlGetState(VectorVariant &vParams, Variant &vResult);
    AUT_RESULT    F_GUICtrlSetBkColor(VectorVariant &vParams, Variant &vResult);
    AUT_RESULT    F_GUICtrlSetOnEvent(VectorVariant &vParams, Variant &vResult);
    AUT_RESULT    F_GUICtrlSetColor(VectorVariant &vParams, Variant &vResult);
    AUT_RESULT    F_GUICtrlSetCursor(VectorVariant &vParams, Variant &vResult);
    AUT_RESULT    F_GUICtrlSetData(VectorVariant &vParams, Variant &vResult);
    AUT_RESULT    F_GUICtrlSetImage(VectorVariant &vParams, Variant &vResult);
    AUT_RESULT    F_GUICtrlSetFont(VectorVariant &vParams, Variant &vResult);
    AUT_RESULT    F_GUICtrlSetLimit(VectorVariant &vParams, Variant &vResult);
    AUT_RESULT    F_GUICtrlSetPos(VectorVariant &vParams, Variant &vResult);
    AUT_RESULT    F_GUICtrlSetResizing(VectorVariant &vParams, Variant &vResult);
    AUT_RESULT    F_GUICtrlSetState(VectorVariant &vParams, Variant &vResult);
    AUT_RESULT    F_GUICtrlSetStyle(VectorVariant &vParams, Variant &vResult);
    AUT_RESULT    F_GUICtrlSetTip(VectorVariant &vParams, Variant &vResult);
    AUT_RESULT    F_GUIDelete(VectorVariant &vParams, Variant &vResult);
    AUT_RESULT    F_GUIGetMsg(VectorVariant &vParams, Variant &vResult);
    AUT_RESULT    F_GUIRead(VectorVariant &vParams, Variant &vResult);
    AUT_RESULT    F_GUISendToDummy(VectorVariant &vParams, Variant &vResult);
    AUT_RESULT    F_GUISendMsg(VectorVariant &vParams, Variant &vResult);
    AUT_RESULT    F_GUIRecvMsg(VectorVariant &vParams, Variant &vResult);
    AUT_RESULT    F_GUISetBkColor(VectorVariant &vParams, Variant &vResult);
    AUT_RESULT    F_GUISetCoord(VectorVariant &vParams, Variant &vResult);
    AUT_RESULT    F_GUIGetCursorInfo(VectorVariant &vParams, Variant &vResult);
    AUT_RESULT    F_GUISetOnEvent(VectorVariant &vParams, Variant &vResult);
    AUT_RESULT    F_GUISetCursor(VectorVariant &vParams, Variant &vResult);
    AUT_RESULT    F_GUISetFont(VectorVariant &vParams, Variant &vResult);
    AUT_RESULT    F_GUISetHelp(VectorVariant &vParams, Variant &vResult);
    AUT_RESULT    F_GUISetIcon(VectorVariant &vParams, Variant &vResult);
    AUT_RESULT    F_GUISetState(VectorVariant &vParams, Variant &vResult);
    AUT_RESULT    F_GUISetTrayTip(VectorVariant &vParams, Variant &vResult);
    AUT_RESULT    F_GUISetTrayBalloon(VectorVariant &vParams, Variant &vResult);
    AUT_RESULT    F_GUISetTrayIcon(VectorVariant &vParams, Variant &vResult);
    AUT_RESULT    F_GUIStartGroup(VectorVariant &vParams, Variant &vResult);
#endif
};
